version: 2
updates:
  # Automatically update GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Automatically update npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "eslint"
      - dependency-name: "typescript"

  # Configuration options for the updates
  open-pull-requests-limit: 10
  commit-message:
    prefix: "chore(deps)"
    prefix-development: "chore(dev-deps)"
  rebase-strategy: "auto"
  versioning-strategy: "increase"
  reviewers:
    - mrcointreau
  assignees:
    - mrcointreau
