version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "eslint"
      - dependency-name: "typescript"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(dev-deps)"
    reviewers:
      - mrcointreau
    assignees:
      - mrcointreau
